cors: "*"
spring.docker.compose.enabled: true
amazon:
  aws:
    access-key: 1
    secret-key: 2
  dynamodb.endpoint: http://localhost:4566/

dynamodb.tableName: OrderTable-local
management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

